- filename: record-0.log
  location: [-356.9, 31.0, 2.2]
  rotation: [0, 1, 0]
  start_time: 0
  type: isetta
  color: red
- filename: record-1.log
  location: [-336.9, 31.0, 2.2]
  rotation: [0, 1, 0]
  start_time: 0
  type: isetta
  color: blue
